# -*- coding: utf-8 -*-
"""P1LAB1_ClayRico.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIjukkvBjDr8HdKY8au2iDb80BBBq0ia
"""



#Rico Clay
# 2/5/2025
# P1lab1
# Using input and print functions

# Get infor from user
f_name = input("Enter your first name: ")
l_name = input("Enter your last name: ")

# Display greeting to user

print("Hello,", f_name, l_name + "!", "Welcome to CTI-110")